version: '3'

services:

  # ===== NATS SERVER ======
  nats-server:
    container_name: nats
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  # === CLIENT GATEWAY ===
  client-gateway:
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - NATS_SERVERS=nats://nats-server:4222

  # ===== PRODUCTS ======
  products-database:
    container_name: products-database
    image: postgres:13.5

    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - 5432:5432

    volumes:
      - ./products-ms/postgres:/var/lib/postgresql/data

  products-microservice:
    depends_on:
      - products-database
    build:
      context: ./products-ms
      dockerfile: dockerfile
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://admin:password@products-database:5432/products?schema=public

  # ===== ORDERS ======
  orders-database:
    image: mysql

    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

    ports:
      - 3307:3306

    volumes:
      - ./orders-ms/mysql:/var/lib/mysql

  orders-microservice:
    depends_on:
      - orders-database
    build:
      context: ./orders-ms
      dockerfile: dockerfile
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=mysql://root:password@orders-database:3306/orders?schema=public

  # ==== AUTENTICACION ====
  auth-microservice:
    build:
      context: ./auth-ms
      dockerfile: dockerfile

    environment:
      DATABASE_URL: "mongodb+srv://admin:AdminMicroservicios@auth.kwrkl.mongodb.net/auth"
      NATS_SERVERS: nats://nats-server:4222
      JWT_SECRET: ALVARO696
